browser = chrome

url = https://online.actitime.com/sprakash1/login.do
username = patraprakashsatya@gmail.com
password = satya123

environment = qa

excelPath = ./src/test/resources/ActitimeData.xlsx

screenshotPath = ./failedscreenshot/